# Generated by Django 5.1.7 on 2025-04-06 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_usersocialauth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('software_engineer', 'Software Engineer'), ('frontend_engineer', 'Frontend Engineer'), ('backend_engineer', 'Backend Engineer'), ('fullstack_engineer', 'Fullstack Engineer'), ('designer', 'Designer'), ('product_manager', 'Product Manager'), ('project_manager', 'Project Manager'), ('qa_engineer', 'QA Engineer'), ('devops_engineer', 'DevOps Engineer'), ('business_analyst', 'Business Analyst'), ('other', 'Other')], max_length=30)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'project', 'role')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('software_engineer', 'Software Engineer'), ('frontend_engineer', 'Frontend Engineer'), ('backend_engineer', 'Backend Engineer'), ('fullstack_engineer', 'Fullstack Engineer'), ('designer', 'Designer'), ('product_manager', 'Product Manager'), ('project_manager', 'Project Manager'), ('qa_engineer', 'QA Engineer'), ('devops_engineer', 'DevOps Engineer'), ('business_analyst', 'Business Analyst'), ('other', 'Other')], max_length=30)),
                ('number_required', models.PositiveIntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_roles', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'role')},
            },
        ),
        migrations.CreateModel(
            name='ProjectRoleSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='projects.projectrole')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_roles', to='users.skill')),
            ],
            options={
                'unique_together': {('project_role', 'skill')},
            },
        ),
    ]
