# Generated by Django 5.1.7 on 2025-04-13 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectmembership_role_alter_projectrole_role'),
        ('users', '0002_usersocialauth'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectrole',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='projectroleskill',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='custom_role_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectroleskill',
            name='custom_skill_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='users.role'),
        ),
        migrations.AlterField(
            model_name='projectroleskill',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_roles', to='users.skill'),
        ),
        migrations.AddConstraint(
            model_name='projectrole',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', False)), fields=('project', 'role'), name='unique_project_predefined_role'),
        ),
        migrations.AddConstraint(
            model_name='projectrole',
            constraint=models.UniqueConstraint(condition=models.Q(('custom_role_name__isnull', False)), fields=('project', 'custom_role_name'), name='unique_project_custom_role'),
        ),
        migrations.AddConstraint(
            model_name='projectroleskill',
            constraint=models.UniqueConstraint(condition=models.Q(('skill__isnull', False)), fields=('project_role', 'skill'), name='unique_project_role_predefined_skill'),
        ),
        migrations.AddConstraint(
            model_name='projectroleskill',
            constraint=models.UniqueConstraint(condition=models.Q(('custom_skill_name__isnull', False)), fields=('project_role', 'custom_skill_name'), name='unique_project_role_custom_skill'),
        ),
    ]
