# Generated by Django 5.1.7 on 2025-05-20 19:15

from django.db import migrations


def populate_role_ids(apps, schema_editor):
    """Create roles for any ProjectRole that's missing a role"""
    ProjectRole = apps.get_model("projects", "ProjectRole")
    Role = apps.get_model("users", "Role")

    # Find all project roles with null role_id
    for project_role in ProjectRole.objects.filter(role__isnull=True):
        # Create a generic role
        role, _ = Role.objects.get_or_create(name=f"Custom Role {project_role.id}")
        project_role.role = role
        project_role.save()


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_projectrole_unique_together_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_role_ids, migrations.RunPython.noop),
    ]
