# Generated by Django 5.1.7 on 2025-05-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_populate_role_values'),
        ('users', '0003_alter_skill_unique_together_remove_role_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectrole',
            name='unique_project_predefined_role',
        ),
        migrations.RemoveConstraint(
            model_name='projectrole',
            name='unique_project_custom_role',
        ),
        migrations.RemoveConstraint(
            model_name='projectroleskill',
            name='unique_project_role_predefined_skill',
        ),
        migrations.RemoveConstraint(
            model_name='projectroleskill',
            name='unique_project_role_custom_skill',
        ),
        migrations.RemoveField(
            model_name='projectrole',
            name='custom_role_name',
        ),
        migrations.RemoveField(
            model_name='projectroleskill',
            name='custom_skill_name',
        ),
        migrations.AddConstraint(
            model_name='projectroleskill',
            constraint=models.UniqueConstraint(fields=('project_role', 'skill'), name='unique_project_role_skill'),
        ),
    ]
