# Generated by Django 5.1.7 on 2025-05-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_projectrole_unique_project_predefined_role_and_more'),
        ('users', '0003_alter_skill_unique_together_remove_role_created_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectrole',
            constraint=models.UniqueConstraint(fields=('project', 'role'), name='unique_project_role'),
        ),
    ]
