# Generated by Django 5.1.7 on 2025-03-24 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('role', models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer'), ('product_manager', 'Product Manager'), ('project_manager', 'Project Manager'), ('qa_engineer', 'QA Engineer'), ('devops_engineer', 'DevOps Engineer'), ('business_analyst', 'Business Analyst'), ('other', 'Other')], default='developer', max_length=30)),
                ('experience_level', models.CharField(choices=[('junior', 'Junior (0-2 years)'), ('mid_level', 'Mid-Level (2-5 years)'), ('senior', 'Senior (5-8 years)'), ('lead', 'Lead (8+ years)'), ('principal', 'Principal/Architect')], default='junior', max_length=30)),
                ('portfolio_link', models.URLField(blank=True, verbose_name='portfolio link')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='users.userprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.skill')),
            ],
            options={
                'verbose_name': 'user skill',
                'verbose_name_plural': 'user skills',
                'unique_together': {('profile', 'skill')},
            },
        ),
    ]
