# Generated by Django 5.1.7 on 2025-03-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_skill_userprofile_userskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_link',
            field=models.URLField(blank=True, verbose_name='GitHub link'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_link',
            field=models.URLField(blank=True, verbose_name='LinkedIn link'),
        ),
    ]
