# Generated by Django 5.1.7 on 2025-03-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('software_engineer', 'Foftware_Engineer'), ('frontend_engineer', 'Frontend Engineer'), ('backend_engineer', 'Backend Engineer'), ('fullstack_engineer', 'Fullstack Engineer'), ('designer', 'Designer'), ('product_manager', 'Product Manager'), ('project_manager', 'Project Manager'), ('qa_engineer', 'QA Engineer'), ('devops_engineer', 'DevOps Engineer'), ('business_analyst', 'Business Analyst'), ('other', 'Other')], default='software_engineer', max_length=30),
        ),
    ]
