# Generated by Django 5.1.7 on 2025-03-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'skill', 'verbose_name_plural': 'skills'},
        ),
        migrations.AddField(
            model_name='skill',
            name='role',
            field=models.CharField(choices=[('software_engineer', 'Software Engineer'), ('frontend_engineer', 'Frontend Engineer'), ('backend_engineer', 'Backend Engineer'), ('fullstack_engineer', 'Fullstack Engineer'), ('designer', 'Designer'), ('product_manager', 'Product Manager'), ('project_manager', 'Project Manager'), ('qa_engineer', 'QA Engineer'), ('devops_engineer', 'DevOps Engineer'), ('business_analyst', 'Business Analyst'), ('other', 'Other')], default='software_engineer', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('name', 'role')},
        ),
    ]
